### ISSUE TITLE
Implement Export-Document Class

### ISSUE THREAD

**Issue by Petschko** [Petschko/dhl-php-sdk#1]
Add missing Class (Export-Document) - Its just a dummy Class now

**Comment by psbbln** [comment]
the export-document class would be great.

**Comment by Petschko** [comment]
I will implement it as soon as I have time then. Was low prio before bec nobody needs it, until now.

**Comment by Petschko** [comment]
Done. See:
https://github.com/Petschko/dhl-php-sdk/commit/47f82b73038274c5b037d4ca92d3eb30e6cf65e9
https://github.com/Petschko/dhl-php-sdk/commit/67b80358bef0d0747375ca7350a2da1087182491
https://github.com/Petschko/dhl-php-sdk/commit/ec5eb3959a1f6d8bb8f0929b72102f502c640243
https://github.com/Petschko/dhl-php-sdk/commit/23f5a93cc19e1b39770d0272492f0abd89cb4cc4
https://github.com/Petschko/dhl-php-sdk/commit/d00481d9878516ed4cb574c4d6311f420e74a1d2
https://github.com/Petschko/dhl-php-sdk/commit/b469104bbe665cb13bfb399d30b35928e34176df
https://github.com/Petschko/dhl-php-sdk/commit/131f5b0b1400ec67dea2258877ae60002a1ad4e8
https://github.com/Petschko/dhl-php-sdk/commit/e6ce1ee3c592b916b731cb33f1edb5902433f2a3

Please test it. If you have issues with it please report them immediately. I never used Export-Document so please check it out
