### ISSUE TITLE
Testing: Export-Document

### ISSUE THREAD

**Issue by Petschko** [Petschko/dhl-php-sdk#10]
Please help me. Tell me if this feature work

**Comment by psbbln** [comment]
i must got something wrong:

$export = new DHL_ExportDocument();
$export->setInvoiceNumer('123');
$export->setExportType('OTHER');
$export->setExportTypeDescription('GOODS');
$export->setTermsOfTrade('DDU');
$export->setPlaceOfCommittal('DE');
$pos = new DHL_ExportDocPosition();
$pos->setDescription('Artikel');
$pos->setCountryCodeOrigin('DE');
$pos->setCustomsTariffNumber('124');
$pos->setAmount('500.00');
$pos->setNetWeightInKG(4);
$pos->setCustomsValue(500.00);
$export->setExportDocPosition($pos);

server error 500...
hmm..

**Comment by Petschko** [comment]
Yeah bec the DHL_ExportDocPosition-Setter are protected. Please use this Function:
````php
	/**
	 * Set values for ExportDocPosition-Class (Ensure that all are set)
	 *
	 * @param string $description - Description of the unit / position
	 * @param string $countryISOCode - Origin Country-ISO-Code
	 * // todo/fixme: is this just an int or float?
	 * @param int|float|string $customsTariffNumber - Customs tariff number of the unit / position
	 * @param int $amount - Quantity of the unit / position
	 * @param int|float $netWeightInKG - Net weight of the unit / position
	 * @param int|float $customsValue - Customs value amount of the unit / position
	 */
	setExportDocPosition($description, $countryISOCode, $customsTariffNumber, $amount,	$netWeightInKG, $customsValue) { /* (...) */ }
````
Its a child function of the ExportDocument class.

Or did you think i should it implement like the way you have set it? (May your way is more common)

I used it as extra function to ensure that all values are set

**Comment by psbbln** [comment]
now it works :-)  (got the label created for a swiss package)
great!

now i have to test if i get the correct export documents back

**Comment by Petschko** [comment]
Please update it. I changed the implementation. I was unhappy about the first implementation.
Now you have to set all Values in
````php
$dhlExportPos = new DHL_ExportDocPosition($description, $countryCodeOrigin, $customsTariffNumber, $amount, $netWeightInKG, $customsValue);
````
then you have set it to the Export-Document:
````php
$dhlExportDoc = new DHL_ExportDocument();
// (...)
$dhlExportDoc->setExportDocPosition($dhlExportPos);
````
See here: https://github.com/Petschko/dhl-php-sdk/commit/230f65c6a7dd6a1ca87d247d9d81ef2495335553

**Comment by psbbln** [comment]
works great.

DHL_Response has to get an additional

		// Set Export Label if exists
		if(isset($response->CreationState->LabelData->exportLabelUrl))
			$this->setExportLabel($response->CreationState->LabelData->exportLabelUrl);
		else if(isset($response->CreationState->LabelData->exportLabelData))
			$this->setExportLabel($response->CreationState->LabelData->exportLabelData);
		else if(isset($response->LabelData->exportLabelUrl))
			$this->setExportLabel($response->LabelData->exportLabelUrl);
		else if(isset($response->LabelData->exportLabelData))
			$this->setExportLabel($response->LabelData->exportLabelData);

**Comment by psbbln** [comment]
thank you so much for your work!
this dhl 2.2 api was freaking me out!

**Comment by Petschko** [comment]
Yeah me too^^ So it work now?

**Comment by psbbln** [comment]
it's works very good. thank you again. great work!
DHL should put it on the entwickler.dhl page

**Comment by Petschko** [comment]
Thanks for testing =) Maybe they should, thanks^^
