### ISSUE TITLE
Multiple Items in Shipment

### ISSUE THREAD

**Issue by petvald** [Petschko/dhl-php-sdk#12]
First of all - thaks for your great package, it helped me a lot. I have found feature which is probably missing in your package (or i didn't find the way how to do it). I need to created Shipment with multiple instances of ShipmentItem. Could you please provide possible solution?

**Comment by psbbln** [comment]
DHL doesnt feature Multi-Parcel-Shipments. So there is no 1/3, 2/3, 3/3
Every Package is handled as single shipment.

**Comment by petvald** [comment]
DHL SOAP API have this feature. But this feature is not implemented in this package. For example here: https://github.com/waldher/dhl-intraship - Multiple Items feature is implemented. 
But I need some solution for php. So I hope it could be somehow possible with this package. Thanks

**Comment by Petschko** [comment]
@petvald I will look how and if I get it implemented... Please note, that your Link is for API-Version 1.
See: https://github.com/waldher/dhl-intraship/blob/master/spec/support/create_shipment_dd_request.xml (Mayor & Minor-Release)

May they have removed it for Version 2? I didn't read anything for multiple Items within the Doku. But I admit, it would make sence to send multiple Items at one. I will look if I can find anything

**Comment by psbbln** [comment]
It's an old feature. New DHL contracts (starting 2013 or so) didn't offer the multi parcel shipments anymore.
The Multi Parcel feature is canceled for all old contracts by august 14th 2017!

so 1 shipment = 1 shipmentitem !

the only thing possible is to put up to 30 <ShipmentOrder> into one xml-request determined by individuell sequence numbers.
https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/operationen/createshipmentorder/beispieldaten

**Comment by petvald** [comment]
@Petschko Thanks for your help. DHL documentation is very poor, but I found there that for Mutliple Items shipment Request should include multiple instances of ShipmentItem objects in ShipmentDetails. Even it makes logical sense that it should be possible because DHL pdf label has information about items count i.e. 1/1.

**Comment by petvald** [comment]
DHL Docs:
https://entwickler.dhl.de/en/group/ep/wsapis/geschaeftskundenversand/operationen/createshipmentorder/ioreference

Point: 2.2.1.7.
ShipmentOrder. Shipment. ShipmentDetails. ShipmentItem
Description:
For every parcel specified, contains weight in kg, length in cm, width in cm and height in cm.
Child elements:
weightInKG
lengthInCM ?
widthInCM ?
heightInCM ?

**Comment by psbbln** [comment]
https://entwickler.dhl.de/group/ep/foren/-/message_boards/message/3201554

**Comment by Petschko** [comment]
So it seems, that they had really removed it in Version 2 o.O What a downgrade imo

**Comment by psbbln** [comment]
the worst is for c.o.d. or export shipments.
there is no way to have c.o.d. shipment anymore! 
you have to manually split the shipment into multi c.o.d. shipments, paying multiple times the c.o.d. fee. (or have one c.o.d. parcel and the others without c.o.d.)
for export you have to provide export documents for each single parcel and split the customs value for each parcel.

**Comment by Petschko** [comment]
Yeah its sad...

I will close this right now, I can't implement it, if they don't have this feature =/ I had an Idea how to add it, but if they don't have it, I can't work with it^^
Sorry about that - Thanks for this discussion =)
