### ISSUE TITLE
[Feature-Request] Api-Method validateShipment

### ISSUE THREAD

**Issue by Dakror** [Petschko/dhl-php-sdk#13]
Hello,
first of all thank you very much for this great library!

I'm currently integrating it for a online shop and wondered if there was a way to add the functionality of validating shipments before creating them, by using the DHL function validateShipment, like $business_shipment->validate() which would not use the createShipmentOrder SOAP call but rather validateShipment in order to see what values are invalid and so on...

If you don't want to or can't implement it i'll maybe submit a PR after eventually implementing it myself :)

Grüße aus München

**Comment by Petschko** [comment]
I can implement it. Since it's a DHL-Function it should be inside the Lib =)

But if you want to implement it, you can do it of course. _(Please tell me if you want to work on it or if I should do it)_

Thanks for the Feature-Request :)

**Comment by Dakror** [comment]
If you got the time, it would be neat if you implemented it :) Thanks in advance.

**Comment by Petschko** [comment]
Added. See: https://github.com/Petschko/dhl-php-sdk/commit/cc40e6370d780c57380f60bf52a2fd03691d025a
I've tested this a little but if there is something wrong please tell me ^^ - For me it works fine so far

**Comment by panconjugo** [comment]
Hey people,

Is it possible to also validate the sender data before creating the shipment? if so, how this could be possible? Thanks.

**Comment by panconjugo** [comment]
Hey again,

I tried doing this:

`$response = $dhl->validateShipment($shipmentOrder);`

and I got an object with the data which I can use to validate, so then I do this:

```
$status_text = $response->getStatusText();
$status_code = $response->getStatusCode();

if($status_text == "ok" && $status_code == 0){

  echo "success";

}
```
But curiously, when I refresh the page, sometimes I get $status_code = 0 and sometimes I get $status_code = 1. Why is that? Here is the response object when everything works well.

`object(Petschko\DHL\Response)#943 (8) { ["manifestData":"Petschko\DHL\Response":private]=> NULL ["statusCode":"Petschko\DHL\Response":private]=> int(0) ["statusText":"Petschko\DHL\Response":private]=> string(2) "ok" ["statusMessage":"Petschko\DHL\Response":private]=> string(45) "Der Webservice wurde ohne Fehler ausgeführt." ["labelData":"Petschko\DHL\Response":private]=> array(1) { [0]=> object(Petschko\DHL\LabelData)#944 (12) { ["statusCode":"Petschko\DHL\LabelData":private]=> int(0) ["statusText":"Petschko\DHL\LabelData":private]=> string(2) "ok" ["statusMessage":"Petschko\DHL\LabelData":private]=> string(45) "Der Webservice wurde ohne Fehler ausgeführt." ["sequenceNumber":"Petschko\DHL\LabelData":private]=> string(1) "1" ["shipmentNumber":"Petschko\DHL\LabelData":private]=> NULL ["label":"Petschko\DHL\LabelData":private]=> NULL ["returnLabel":"Petschko\DHL\LabelData":private]=> NULL ["exportDoc":"Petschko\DHL\LabelData":private]=> NULL ["codLabel":"Petschko\DHL\LabelData":private]=> NULL ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) } } ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) } `

And here is the object when the status code is 1:

`object(Petschko\DHL\Response)#943 (8) { ["manifestData":"Petschko\DHL\Response":private]=> NULL ["statusCode":"Petschko\DHL\Response":private]=> int(1) ["statusText":"Petschko\DHL\Response":private]=> string(26) "Some Shipments had errors." ["statusMessage":"Petschko\DHL\Response":private]=> string(48) "ok;Der Webservice wurde ohne Fehler ausgeführt." ["labelData":"Petschko\DHL\Response":private]=> array(1) { [0]=> object(Petschko\DHL\LabelData)#944 (12) { ["statusCode":"Petschko\DHL\LabelData":private]=> int(0) ["statusText":"Petschko\DHL\LabelData":private]=> string(2) "ok" ["statusMessage":"Petschko\DHL\LabelData":private]=> string(45) "Der Webservice wurde ohne Fehler ausgeführt." ["sequenceNumber":"Petschko\DHL\LabelData":private]=> string(1) "1" ["shipmentNumber":"Petschko\DHL\LabelData":private]=> NULL ["label":"Petschko\DHL\LabelData":private]=> NULL ["returnLabel":"Petschko\DHL\LabelData":private]=> NULL ["exportDoc":"Petschko\DHL\LabelData":private]=> NULL ["codLabel":"Petschko\DHL\LabelData":private]=> NULL ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) } } ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) } `

Do you know the reason of this? am I missing any other setting?

Thanks.
