### ISSUE TITLE
Label output size

### ISSUE THREAD

**Issue by Petschko** [Petschko/dhl-php-sdk#14]
I've got a Feature-Request about adjusting the size for the output Label.

I never read anything about it in the DHL-Dokumentation, if someone knows anything about it please tell me. (Like if there is such a feature)

If there is such a function to adjust the Label-Size for printing, I will implement it as soon as possible =)

**Comment by psbbln** [comment]
the labelsize must be set within the dhl-geschaeftskundenportal
VERSENDEN / EINSTELLUNGEN / ALLGEMEINE EINSTELLUNGEN
or
SHIP / BASIC SETTINGS / GENERAL

you can't set labelsize via the api

**Comment by dasistdaniel** [comment]
Hi, I asked for this feature (per mail) 
We're currently using the Polling Client and a Zebra GK420d to print the Labels. 
The settings are set to 103mm x 199mm and are also set in the Geschäftskundenportal.

When i create a Label with the Dev Account it's always in DIN A5 Format. 

I guess this can't be changed and I have to try till I can test it in production Mode?

**Comment by psbbln** [comment]
cant remember but it can be that the sandbox account only creates the A5 label.
as you dont have access to the settings of the sandbox user you may just go with it and get approval from dhl.

in live mode:
if you have different users for the geschäftskundenportal make sure to set the label size correctly for the username used for the api!!!
"Versandschein" must be set to Common Label Thermodruck 103x199

if everything is set correctly in the geschäftskundenportal make sure to have the standard printer settings for the zebra set to 103x199 as well!!!

**Comment by Petschko** [comment]
Thanks for your fast reply @psbbln =) So you have set it by yourself within the geschäftskundenportal
