### ISSUE TITLE
Check if local WSDL-Files are up-to-date

### ISSUE THREAD

**Issue by Petschko** [Petschko/dhl-php-sdk#15]
DHL say we should store the WSDL-Files local (improved performance, less traffic & better for DHL-Servers), thats done with this SDK. But I didn't implement the feature where the SDK checks (for example once a day), if the File(s) is(/are) up-to-date...

**Comment by hnast** [comment]
Why not just use the WSDL caching feature of PHP?

**Comment by Petschko** [comment]
Ah I didn't know about this, yeah this is a great. I will dig through this.

**Comment by Petschko** [comment]
Removed use of local files. Since PHP stores them by itself for 1 Day - See:
https://github.com/Petschko/dhl-php-sdk/commit/f40fc4a160a917ab2c08cdbbba7cab652f9c60e2

If you want to use local file you have to set it in the Custom URL-Field.

The text on the DHL-Page was for other language developers I guess _(For these where not an auto Cache System exists)_
But I didn't know by myself, until today, that php stores WSDL-files by itself. So thanks @hnast  =)
