### ISSUE TITLE
Call of getLabel after getShipmentLabel returns null instead of label

### ISSUE THREAD

**Issue by hnast** [Petschko/dhl-php-sdk#16]
When trying to request an already created shipment label via $dhl->getShipmentLabel and then calling $response->getLabel() the method returns null.

My solution was to simply add the label response type to the creation of the DHL_Response object in the method getShipmentLabel definition (DHL_BusinessShipment.php:940)

**Comment by Petschko** [comment]
Ah yeah... I simply forget to add this. Thanks for the report!
Did you use the Base64-Label type? I guess, because there was no issue with the URL-Label. I will add this later

**Comment by hnast** [comment]
You guessed right - I used the Base64-Label.

**Comment by Petschko** [comment]
Added: https://github.com/Petschko/dhl-php-sdk/commit/5b42735b762226e98da158cbd03bc536a3f67596
