### ISSUE TITLE
Return-Label only

### ISSUE THREAD

**Issue by netfabs** [Petschko/dhl-php-sdk#22]
Hi there!

I'd like to build an application for a customer.

Is there a way to get the normal label in the first step and only if its nessesary to get der return-label?

In my case the function $dhl->getReturnLabel() is not working.

Thanks!

**Comment by EddyFK** [comment]
As far as $dhl is defined as a new DHL_BusinessShipment instance, getReturnLabel needs to be defined in there i guess. I have a similar problem of hooking other stuff there...

**Comment by netfabs** [comment]
I would like to get de ReturnLabel in a separate call only if the customer would like to send his paket back...

**Comment by Petschko** [comment]
Hm as far I know you have to set some specific values for that else you get both (Label & Return-Label) in one...

I never tried to get them separately, because my company just need both. But it make sense, if you want your User to print the return label^^

I will search for this, may someone here know how to do it? And may we can build in a switch for that ;P

**Comment by netfabs** [comment]
Thanks, that's awesome!

**Comment by Petschko** [comment]
Hello I found this in the IO-Reference:

> CreationState.LabelData.returnLabelUrl - String | Optional
If label output format was requested as 'URL' via LabelResponseType, this element will be returned. It contains the URL to access the PDF label. This is default output format if not specified other by client in labelResponseType.
**Depending on setting in customer profile all labels or just the returnshipmentlabel.**

So I guess, you have to set this up in your Profile and not via the API...

**Comment by arumcomputer** [comment]
Where do I have do set this exactly? I can't find this at the developer page of dhl or in my profile there.

**Comment by Petschko** [comment]
Meine Firma benötigt IMMER Retoure UND Hinlieferung, daher habe ich mich damit nicht weiter auseinander gesetzt. Dennoch denke ich, dass NUR Retoure nicht möglich ist mit dieser API. Sofern es doch möglich ist bitte bescheid sagen, dann baue ich eine Möglichkeit ein, dieses auch mit dem Framework zu erzeugen!

Es kann natürlich auch sein, dass man dafür eine andere API von DHL benötigt. (Meine Firma hatte erst irendeine andere, die glaube ich NUR für Retoure war)... Ich bin da auch nicht so drinnen, da es ein ziemliches Chaos ist, was deren Infos angeht, einfach mal dort nachfragen =)
