### ISSUE TITLE
How to set up GoGreen?

### ISSUE THREAD

**Issue by EddyFK** [Petschko/dhl-php-sdk#23]
Hy folks, i tried to add GoGreen Support, but on the label it's not showing:

```
$service = new DHL_Service();
$service->setGoGreen(1);
$service->setPremium(1);
...
$dhl->setService($service);
```
Premium is working though and uses the same semantic. A closer look (my php skill is not the best) let me to DHL_Service.php line 1155:

```
if($this->getPremium() !== null) {
	$class->Premium = new StdClass;
	$class->Premium->active = (int) $this->getPremium();
}
```
this kind of definition is missing for GoGreen, but adding the same for green doesnt seem to solve the problem:
```

if($this->getGoGreen() !== null) {
	$class->GoGreen = new StdClass;
	$class->GoGreen->active = (int) $this->getGoGreen();
}
```

Any idea? Am i missing something ?

**Comment by Petschko** [comment]
I'm sorry but DHL didn't implmenet this right now... They just add this value to set this but it won't do anything...

You can read my Post in the DHL-Forums about this: https://entwickler.dhl.de/group/ep/foren/-/message_boards/message/3222944

The answer of my Problem was: _(German - I will translate it later)_
> Außerdem ist GoGreen nicht (mehr) über die API zu (de-) aktivieren. Das kann evtl. im Kundenportal eingestellt werden, oder muss vom GK-Vertrieb eingestellt werden.

Hope that helps

**Comment by Petschko** [comment]
> My guess is that all EPKs ending with "01" create that green label, but not sure!

No, this is wrong. My company used 01 the first time and we don't get the GoGreen-Label because we don't have set this up.

> But it's still a documentation problem, as on their API knowledge base the GoGreen is still inside (you need a login to view this):

Yeah I know the Documentation... As they say, may they implement that in later Versions that's why I also added this here. The Documentation of them is not the best to be honest^^ They should at least Note that this is unusable...
