### ISSUE TITLE
Better address support

### ISSUE THREAD

**Issue by EddyFK** [Petschko/dhl-php-sdk#25]
Hy folks, recently i spotted a problem with the address validation aka full street address. Its works fine for Germany but really bad for anything else. I found that php address checker, which parses the address through google: http://www.jayjohnston.com/php/parse-addresses-in-php-using-google-geocoding

I changed the address check in line 295/Addresses.php:
```php

public final function setFullStreet($street) {
  
$url = 'http://maps.googleapis.com/maps/api/geocode/json?sensor=false&address='.urlencode($street); 
  $results = json_decode(file_get_contents($url),1); 
  $parts = array( 
    'street'=>array('route'), 
    'number'=>array('street_number')
  ); 
  if (!empty($results['results'][0]['address_components'])) { 
    $ac = $results['results'][0]['address_components']; 
    foreach($parts as $need=>&$types) { 
      foreach($ac as &$a) { 
        if (in_array($a['types'][0],$types)) $address_out[$need] = $a['short_name']; 
        elseif (empty($address_out[$need])) $address_out[$need] = ''; 
      } 
    } 
  }
	
$this->setStreetName($address_out['street']);
$this->setStreetNumber($address_out['number']);
	
}
```
Hope it helps somebody :D

**Comment by EddyFK** [comment]
What would be cool is to check the country first and if its NOT Germany, than use the google checkup and if it IS Germany use the simple Address check from before. That way we wouldnt need to go through the google api only if necessary. What do u think?

**Comment by Petschko** [comment]
Hm I'm not a fan of throwing stuff to Google... _(Just my opinion)_ You should try to do such stuff without Google, so that you doesn't depend on them. To be honest, it makes stuff easier

Your solution with the Country-Check sounds somewhat better, then you just require the Google-API if required.

It's a Solution, but can you please tell me first, what doesn't work? (Adress Examples) =)

May I just have to change the Regex? So Multiple Adresses would be very helpful!

**Comment by EddyFK** [comment]
Yes, i tried the following address:

```
name:Lethal Amounts
full street: 1226 W 7th St
town: Los Angeles
zip: 90017
state: CA
country: United states
```
This creates an hard validation error targeting the full street. When i change to this...
```
full street: W 7th St 1226
```
... the error disappears, but the respond looks like this:
```
<ns1:streetname>W</ns1:streetname>
<ns1:streetnumber>7th St 1226</ns1:streetnumber>
```
Which is wrong as DHL will output on the label this wrong format: W 7th St 1226 instead of 1226 W 7th St. We need to find a better way here... Google works so far pretty good, but sure i will add a regex in case of any error!

**Comment by Petschko** [comment]
Uhm, to be honest I don't know by myself which is the number of "1226 W 7th St"

It is 1226 or 1226 W or 1226 W 7th? Can you give me some more different addresses, which may don't match the regex?
Its hard to change a regex with just 1 adress^^

**Comment by EddyFK** [comment]
Fair enough ;) the number in that case would be: 1226, street name: W 7th str. Its common in the us and other countries to have the street number in front:

US address format: http://www.bitboost.com/ref/international-address-formats/united_states/
UK address format: https://personal.help.royalmail.com/app/answers/detail/a_id/81/~/clear-addressing---how-to-address-your-mail

**Comment by Petschko** [comment]
Thanks for the Links, I have a look at it.

I think it's not a basic feature of this SDK, so I will add it later.

**Comment by Petschko** [comment]
I decided myself to remove the `setFullStreet` method in future versions... It has to many failures and should be solved by each person individualy.

I will mark this function as deprecated in version 0.3
