### ISSUE TITLE
Missing the API Method getVersion()

### ISSUE THREAD

**Issue by Dakror** [Petschko/dhl-php-sdk#26]
I would like to use the `getVersion()` Method of DHL as a simple check whether the user has entered valid API credentials. 
I will implement it myself for my software, but a more robust and more coherent to the style of the library implementation would be appreciated. The request itself is very straightforward.

Any other easy implementation of a simple credentials validation check would be just as fine. I just suggested the getVersion method since it's an easy request that does not need parameters

**Comment by Petschko** [comment]
I see, yeah I didn't implemented that function yet, but you have a Point. I will add this to the todo list...

**Comment by Petschko** [comment]
Implemented it in my Local-Code... I will push it when I'm done with the Documentation

**Comment by Petschko** [comment]
Done, see:

https://github.com/Petschko/dhl-php-sdk/commit/5364836f31dd5950428ee7f836ec2ca09093c580
