### ISSUE TITLE
Request several labels in one call

### ISSUE THREAD

**Issue by chrisp1001** [Petschko/dhl-php-sdk#29]
The DHL API allows to create up to 30 shipment labels per SOAP call. In test.php there's only one label generated. Is it possible to create several labels in one call?

**Comment by Petschko** [comment]
Are you sure that you are not speak about an other DHL-API? I read the Doku and never saw stuff with multiple Labels.
There are also some features removed in API-Version 2 (Like multiple Items in Shipping's etc)...
Do you have a Link or something else where I can take a look at?

**Comment by chrisp1001** [comment]
Login to the Developer Portal and check:

https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/operationen/createshipmentorder/beispieldaten

Now have a look at "Request DHL Paket (V01PAK)":

`<ShipmentOrder>` can be repeated 1 to 30 times according to the comment: `<!--1 to 30 repetitions:-->`

**Comment by Petschko** [comment]
I see. I just used the I-O-Doku, since the rest is spread over the entire Page (As comment lol...)...

I will test it local and implement it if it works.
Thanks for telling me the missing feature! =)

**Comment by chrisp1001** [comment]
Your welcome :)

**Comment by mel-pashtet** [comment]
Hi. You will fix this issue? Now I need this feature. I need create request (GetLabel, createShipmentOrder) with several items. Thank You.

**Comment by Magellanth** [comment]
Hi, this feature would be really important to me, can i offer any help?
Had a quick view in your code and i guess the main problem ist that the used StdClass structure cant model the repeating xml structure?

**Comment by Petschko** [comment]
The main Problem is, I build everything as single Shipment in the Main-Class `BusinessShipment`, because I didn't saw the Comment with multiple Shipments. (It don't exists in the I/O-Doku, which I used to Program this SDK)

I'm currently implement it, I opened the multi-labels Branch, where I want to test and do the changes: https://github.com/Petschko/dhl-php-sdk/tree/multi-labels

I think I'm done this week with it

**Comment by Magellanth** [comment]
In this case i like your timing (as well as your library)
