### ISSUE TITLE
Cannot print label trough webservice after `doManifest`

### ISSUE THREAD

**Issue by cedricziel** [Petschko/dhl-php-sdk#30]
Hi,

I'm currently trying to print a label after manifesting a shipment by number, which works.

Right after manifesting the shipment, I can`t print the label anymore - neither through the old url, nor by using `$dhl->getShipmentLabel($shipmentNumber)`. 

Is this a limitation of the sandbox or a mishandling of the API through the library?

**Comment by Petschko** [comment]
Yes my Company has the same Problem. I solved that by saving the Base64-Label Data. It seems that you can't use the URL after the Shipment is "Done" aka after you do the Manifest or the "Shipment-Date" is over

**Comment by cedricziel** [comment]
Alright and you use it the same way in production?

**Comment by Petschko** [comment]
Yes. I'm unsure why you can't use the URL after that. But maybe DHL try to save Disk space with this or whatever^^

Last time we need to reprint a Label and it was gone. So we just reprint it via the DHL-Portal - But this can be a pain if you have to do that with a lot of Labels, so I suggest to save the Base64-Label Data

**Comment by cedricziel** [comment]
Alright, we now use the same mechanism. Thx.
