### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load [...]

### ISSUE THREAD

**Issue by obrunsmann** [Petschko/dhl-php-sdk#31]
Hey Guys,

just did all the steps from readme but getting following error:

```
[Symfony\Component\Debug\Exception\FatalErrorException]                                                              
  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-a  
  pi/2.2/geschaeftskundenversand-api-2.2.wsdl' : failed to load external entity "https://cig.dhl.de/cig-wsdls/com/dpd  
  hl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl" 
```

When I try to fetch WDSL URL in Browser it works fine.

**Comment by Petschko** [comment]
Hm may your Server doesn't allow connections outside? You can still download their file and place it local.

In my Company our Server doesn't allow access to unknow File-Extensions (Whitelist) - So I just added the ".wsdl" File-Extension to the Whitelist and it works^^

**Comment by Petschko** [comment]
Any News here?

**Comment by obrunsmann** [comment]
Sorry, forgot to update ticket here. Seems that the problem is an issue with openssl. I had the same problem one day later with Amazon S3. The CA Certificate is broken.

So nothing to do here ✌️

**Comment by clicktrend** [comment]
Hi @Petschko ,

I'm facing the same error. I'm using openssl 1.1.1c and curl is throwing error

`curl -i https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl`
`curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small`

DHL has a old certificate. To get it work new ciphers must be provided to curl command.

` curl -i --ciphers  'DEFAULT:!DH'  https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl`

**Comment by clicktrend** [comment]
This helps

    $auth_params = array(
			'login' => $this->getCredentials()->getApiUser(),
			'password' => $this->getCredentials()->getApiPassword(),
			'location' => $location,
			'trace' => 1,
			'stream_context' => stream_context_create([
				'ssl' => [
					'ciphers'=>"DEFAULT:!DH"
				]
			]),
		);

But unfortunately your function is private and I cannot override it

**Comment by Petschko** [comment]
Do you think its a good idea to either:
- Include this by default
- Make the function protected

I can look into that, feel free to let me know more about this!

**Comment by clicktrend** [comment]
OpenSSL enforce a non-weak DH key because of the Logjam attack. [Link](https://stackoverflow.com/questions/36417224/openssl-dh-key-too-small-error). So it makes sense to keep this security enhancement.

The best is that DHL changes its weak certificate. May be they will do it so this issue will be obsolet. In my opinion making the function protected is the best option.

**Comment by Petschko** [comment]
Thanks for the information!

I made relevant functions protected, so they can overwritten! See: https://github.com/Petschko/dhl-php-sdk/commit/b2cc6548d60ca7e9cf5ea58866131240dc1d45d6
