### ISSUE TITLE
Return label shipment number

### ISSUE THREAD

**Issue by petvald** [Petschko/dhl-php-sdk#32]
Can you please help me how to get shipment number of return label?
Function getShipmentNumber() return number of package which goes to receiver but i need also to save number of the return package...

**Comment by Petschko** [comment]
You must set this somewhere in your Customer Profile, that you want get both separated^^

See: https://github.com/Petschko/dhl-php-sdk/issues/22#issuecomment-315151381

I know this is annoying but that's the only way, how you can get both labels separated (plus their values)
