### ISSUE TITLE
setAddressAddition ignored for national shipments

### ISSUE THREAD

**Issue by Mwni** [Petschko/dhl-php-sdk#33]
Hi,

first of all, a huge thanks for this library. It has saved me hours of painful work.

Now, when I try to add a additional line to the receiver address, it does not show up on the shipping-label.
The DHL-Docs say, the addressAddition field is for international shipments only.

Are there any other possibilities? Sometimes the address additional is required, otherwise the shipment cannot be delivered and is returned.

**Comment by Petschko** [comment]
Hm~ I can't implement stuff, which is not Supported by DHL. At best you ask them in the Forums, I will also watch the Topic in their Forums, may I can help you then.

**Comment by Mwni** [comment]
Thank you for the quick response, petschko!
I will ask them, and post here again, if anything helpful comes out of it.

**Comment by Petschko** [comment]
Any News here?

**Comment by Mwni** [comment]
Haven't managed to ask DHL about this, since last time I checked, their forum was down.

However, the current workaround is to put this address-addition into the "Name2" field. Not pretty, but works.

The forum is up again, [here](https://entwickler.dhl.de/group/ep/foren/-/message_boards/message/4457563?p_p_auth=bddCc3A0) is the thread. I'll check back on new insights.

**Comment by Mwni** [comment]
Got a response from DHL: Use Name2 or Name3 field.
So I guess we will have to live with it... ^^

**Comment by Petschko** [comment]
Alright! Sorry that I could not help you really much with this one

**Comment by cottton** [comment]
Since i found this by web search I just wanna add here that there is still no change.
adressAddition gets ignored on nationally addresses.
"name3" works and gets printed above the street line.

**Comment by Petschko** [comment]
Yeah, it was already mentioned!
