### ISSUE TITLE
I need a version without COMPOSER

### ISSUE THREAD

**Issue by burhan-kun** [Petschko/dhl-php-sdk#35]
Please help me, i have included includes/noncomposer.php but i become only Errors. What can i do?

**Comment by Petschko** [comment]
Hello, please tell us what is/are the errors (By including the Message/s)^^

**Comment by burhan-kun** [comment]
Hallo, tut mir leid, hat sich geklärt. Ich habe nachdem Include von Noncomposer die ganzen "use's" auch gelöscht gehabt, aber anscheinend sollten die immernoch drin bleiben.

👍
