### ISSUE TITLE
$receiver - Add CompanyName?

### ISSUE THREAD

**Issue by burhan-kun** [Petschko/dhl-php-sdk#36]
Hello,

how i can add CompanyName and Street2 to the Receiver?

Thanks

**Comment by Mwni** [comment]
Neither is possible. You will have to rely solely on the "Name2" field.

One thing you could do however, if you have to get the company name and street2 on the label:
- put the company name on the "Name" field
- put the recipients name on the "ContactPerson" field
- put the additional street on the "Name2" field

I've already contacted DHL about this inconvenience, but they do not seem to care.

**Comment by burhan-kun** [comment]
Hi thanks for your reply.

I don't find the Function for ContactPerson and Name2. I find it only for $sender not for $receiver?

// Mostly used in bigger Companies
$sender->setContactPerson((string) 'Peter Dragicevic');

Can i use this like this:
// Mostly used in bigger Companies
$receiver->setContactPerson((string) 'Peter Dragicevic');  

?

**Comment by Petschko** [comment]
Hello,

yes you can use it also on the Receiver-Class. Both classes have the same parent Class `SendPerson` (https://github.com/Petschko/dhl-php-sdk/blob/master/includes/SendPerson.php)
