### ISSUE TITLE
Service NamedPerson doesnt work

### ISSUE THREAD

**Issue by OliverTempel** [Petschko/dhl-php-sdk#38]
Create a shipment and add extra service namedPersonOnly doesnt work.

**Comment by Petschko** [comment]
Hey what should that Service do?

Some Services are implemented from DHL but you have to set them up via your Customer Dashboard, are you sure that this Service is supported via the API?

For example GoGreen is not enabled via the API but DHL build that in the API (For what reason ever)

**Comment by OliverTempel** [comment]
Deliver Package to a named Person, 
try to create a new delivery @ www.dhl-geschaeftskundenportal.de and i dont find an option for this.
So i think it is an unused service.

**Comment by OliverTempel** [comment]
Arg in German it is the option "persönliche Übergabe" and this option can be booked.

**Comment by Petschko** [comment]
I think this could be that value in the Service Class:

````php
	/**
	 * Contains if personal handover is enabled
	 *
	 * Note: Optional
	 *
	 * @var bool|null $personalHandover - Is this enabled | null uses default
	 */
	private $personalHandover = null;
````

You can use it like this:
````php
    $service = new \Petschko\DHL\Service();
    $service->setPersonalHandover(true); // Set the Service to true to enable it

    // Add it to the Main-Class (BusinessShipment)
    $businessShipmentInstance->setService($service);

    // Rest works like normal (sending the request and ahndling the response)
````

**Comment by OliverTempel** [comment]
Thanks

**Comment by OliverTempel** [comment]
Got reply: Der angegebene Service ist nicht bekannt.

**Comment by Petschko** [comment]
Please ask then in the Developer-Forums:
https://entwickler.dhl.de/

You can use the helper function to get the XML-Request, usually they want see your XML-Request:

````php
// (...) All you stuff for dhl including requests etc here

// Show your XML-Request AFTER sending it to DHL:
echo $businessShipmentInstance->getLastXML();
````

**Comment by OliverTempel** [comment]
Rückmeldung von DHL:
mit
<NamedPersonOnly active="1"/>
sollte es funktionieren, es ist der Nachfolgeservice von "Eigenhändig"

**Comment by Petschko** [comment]
Achso alles klar^^ Diesen Wert gibt es ebenfalls in der Service Klasse. Dementsprechend einfach NamedPersonOnly  auf true setzen^^

**Comment by OliverTempel** [comment]
Wenn ich das richtig gesehen habe dann ist das nen Textfeld :) nix mit auf true setzen

**Comment by Petschko** [comment]
Es ist die XML-Version. Mein SDK wandelt dies am ende in genau dieses Format um. Sollte es nicht funktionieren kannst du mir den XML Code gerne Posten.

Wenn du selbst alles in Plain XML machen möchtest, benötigst du dieses SDK nicht =)
