### ISSUE TITLE
Return-Label

### ISSUE THREAD

**Issue by Petschko** [Petschko/dhl-php-sdk#4]
Hello,

I was not able to test if the Return-Label works (no Test-Data found) - Please test it, if you can...

If you know Test-Data for Return-Label, please write them here, so that I can include them (or do it by yourself =))

**Comment by Petschko** [comment]
Seems to work pretty well

**Comment by petvald** [comment]
I have a huge problem with getting a return label. Everything is working fine, but i can´t get Return label. I set everything as is described in example but return label is always null in response object. 
Can you please post here a short code how to setup return label or write what needs to be done to get it working. Thanks very much

**Comment by Petschko** [comment]
You find the Return Label usually in the same Document with the normal label both in 1. You only find the Return Label seperated if you set this up in your DHL-Account

**Comment by petvald** [comment]
Thank you, you helped me a lot. I did not expect it is there... :-)

**Comment by Petschko** [comment]
Had the same issue before =)
