### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by alex-LE** [Petschko/dhl-php-sdk#41]
Hi, for logging purposes we would like to log als the complete request sent to DHL.
Currently all methods/properties are private.
Does it make sense to create a pull request to get the last sent data or something similar?

Alex

**Comment by Petschko** [comment]
There is actually a function that shows you the last send XML but this is not what you are looking for?

**Comment by alex-LE** [comment]
How is the function called? This will be enough, we just want to have a way to log it in case of an error.

**Comment by Petschko** [comment]
Ah okay^^

The method is in the "BusinessShipment"-Class and is called `getLastXML()`. Its must be called after sending a request to DHL

**Comment by alex-LE** [comment]
thats perfect, thanks
