### ISSUE TITLE
validateShipment: StatusCode 1 but everything is Ok

### ISSUE THREAD

**Issue by dasistdaniel** [Petschko/dhl-php-sdk#43]
Hi, 
i'm trying to validate my adresses before i send them create a label, but sometimes i get 
some wrong information back.

```
StatusCode: 1
StatusText: Some Shipments had errors.
StatusMsg: ok;Der Webservice wurde ohne Fehler ausgeführt.
```

If i try to validate it again it works and gives me the correct Status:

```
StatusCode: 0
StatusText: ok
statusMsg: Der Webservice wurde ohne Fehler ausgeführt.
```

In the following Screenshot you see some test javascript, 
which gets the data from my test.php.

The entries were all tested with the same adress.
![github_dhl](https://user-images.githubusercontent.com/2505795/36537958-04ac31ae-17d2-11e8-9207-42d88467fa74.jpg)
(every request is about 10-30 seconds apart)

**Comment by Petschko** [comment]
StatusCode "1" was created by me, to see when a minor Error occoured, like an non-existing Adress (DHL always returns 0 then)
The Message "Some Shipments had errors" is from DHL (If this message is set and Code 0, this SDK returns Code 1).

And you are using the same Adress? Or occours this with different Adresses?

**Comment by dasistdaniel** [comment]
This was all with the same adress. 
I know the adress is correct, I tested it with my own, and from like 10 tries in a row and sometimes I got one "Error"

**Comment by Petschko** [comment]
Strange...

But I think it's a Problem with DHL, since the SDK just reads the response and you get Code 1 always when DHL gives a hint ("Some Shipments had errors").

I don't know why but I think you should report this bug to them (Don't mention Status-Code 1, but the Status-Message and Text)

**Comment by attikov** [comment]
Hi,
I'm not using this lib but I encounter the same behavior and this was the only hit on google.
And just to add, I'm on the sandbox from DHL.

**Comment by Petschko** [comment]
It would be interesting to know, if this happens also with other libs, because I still think thats a DHL-Bug (Because I just set the status by the answer from DHL) And when the answer is faulty, I think its from DHL

**Comment by attikov** [comment]
It must be from DHL, but the chances that somebody responses in this manner from DHL are very low.
Could be also a sandbox problem, sadly I don't have a live account yet. Maybe Daniel has one and could confirm.

**Comment by dasistdaniel** [comment]
I'm currently using both Sandbox and Live mode. So this bug appears in both. 
Does anyone know if theres any official way to file a bug report for the official DHL API?

**Comment by attikov** [comment]
Thx for the info Daniel.
You can contact DHL support over the entwicklerportal. Either via forum or opening a support ticket.
However, I've made some test and it turns out that instead of 
"ValidateShipmentResponse.Status"
it's better to parse and analyze:
"ValidateShipmentResponse.ValidationState" array.

It contains the responses for every order, and meanwhile it has also some strange things like
returning the same message more than once, at least the StatusCodes and StatusText are consequent.

**Comment by Petschko** [comment]
@panconjugo as you see in this issue, this is a problem from DHL, so if you want a change on this issue you need to contact them, since we can't do anything about this.

OP created 10 same requests and send them to DHL, but got different responses

**Comment by RizzoRat** [comment]
Petschko: From my experience, a 1 response with "ok;Der Webservice wurde..." happens in two cases:
a)  Requests take too long. Just try the same address over and over, some the SDK returns fast with 0 response, on some it takes about 3 seconds and you get a 1 response. My educated guess: That's a timeout on something, possibly socket timeout...
b) When the request processes more than one shipment, for example, it could happen that some are okay, and some have a warning or even an error! One has to check all data separately using response->countLabelData() and response->getLabelData. That's what atticov just stated earlier

b) is a matter of correct SDK usage (not very well explained in the examples/docs, tbh) but a) could be an internal SDK issue.
So you might want to check for timeouts, Petschko?
(Simply try to validate a single valid address over and over, and I guess you can debug easily. When there's load at DHL during business times the percentage of such erroneous "soft failures" will be at 5 to 30% from my experience...)

**Comment by attikov** [comment]
Hi again. It must be an SDK issue then I've running our DHL client app over a year now without any problems. And AFAIR, I'm not evaluating the "main" response code, but the ones in the response array for every shipment one by one.

**Comment by Petschko** [comment]
@attikov thanks for the tip, that could may solve the problem! I will look how to implement it best. I still want to provide the response-code for the (global) request itself, for example what kind of response-code should provided if on 3 Shipment items every Item has a different response-code? Should I drop the "global" response code?

What do you think?

**Comment by RizzoRat** [comment]
I'd keep it as it is. A global response status of 1 indicates the user has to look closer and iterate the array, and it is safe to iterate when there was only one. 
However, currently you sometimes get the global response of 1 erroneously (one shipment with stat 0 in the array, but global stat is 1)

**Comment by Petschko** [comment]
I could drop it on single Shipments (and use the single Shipment-Code as global status-code) but it's still weird why it happens in single shipments even if the shipment itself has no errors

**Comment by Magellanth** [comment]
I just can tell that i had the same problem here. I just did an override of the status in case of:
`if($response->getStatusCode() === Response::DHL_ERROR_WEAK_WARNING
                    && $statusMessage === "ok;Der Webservice wurde ohne Fehler ausgeführt.")`
Never had any issue with that workaround and we shipped tens of thousands of packages.

**Comment by Petschko** [comment]
Thank you so much @Magellanth that's a quite simple but effective solution!

I will implement this. Theoretically the Status-Code 1 does not exists on DHL-Responses it was a custom one made by me, so its normal this bug can't appear in other programs

I will overwrite this function in Response.php, for those who don't want to wait can do their self the hotfix: (Else wait until I push the next version)
````php
	/**
	 * Check if the current Status-Code is correct and set the correct one if not
	 */
	private function validateStatusCode() {
		if($this->getStatusCode() === 0 && $this->getStatusText() !== 'ok')
			$this->setStatusCode(self::DHL_ERROR_WEAK_WARNING);

		// Fix the DHL-Error Weak-Warning-Bug
		if($this->getStatusCode() === self::DHL_ERROR_WEAK_WARNING && $this->getStatusMessage() === 'ok;Der Webservice wurde ohne Fehler ausgeführt.')
			$this->setStatusCode(self::DHL_ERROR_NO_ERROR);
	}
````

**Comment by RizzoRat** [comment]
beware, this will also unintentionally "fix" the response in case there is more than one shipment and one of them actually HAS an issue! If at all a hotfix, do it only after iterating all shipments and when all of them had a response of DHL_ERROR_NO_ERROR. (For us, it's highly important for example when submitting manifests)

**Comment by attikov** [comment]
Here is my implementation which runs over a year and I had no bad feedback since then.
It's delphi (pascal) but you will surely understand whats going on:

lCreateShipmentOrderResponse := lAPIService.createShipmentOrder(..) //here I submitting the shipment

 for i := 0 to High(lCreateShipmentOrderResponse.CreationState) do
begin
....
        lLabelData := lCreateShipmentOrderResponse.CreationState[i].labelData;
        if lLabelData.Status.StatusCode <> 0 then
          Status[i].Error := True
        else if Comparetext(lLabelData.Status.StatusText, 'ok') <> 0 then
          Status[i].Warning := True;
....
end;

and I'm returning Status array and evaluating what to do...

**Comment by Petschko** [comment]
> 
> 
> beware, this will also unintentionally "fix" the response in case there is more than one shipment and one of them actually HAS an issue! If at all a hotfix, do it only after iterating all shipments and when all of them had a response of DHL_ERROR_NO_ERROR. (For us, it's highly important for example when submitting manifests)

I rewrote the function now, this could be more your tastes!

````php
	/**
	 * Check if the current Status-Code is correct and set the correct one if not
	 */
	private function validateStatusCode() {
		if($this->getStatusCode() === self::DHL_ERROR_NO_ERROR && $this->getStatusText() !== 'ok')
			$this->setStatusCode(self::DHL_ERROR_WEAK_WARNING);

		// Fix the DHL-Error Weak-Warning-Bug
		if($this->countLabelData() === 1) {
			// ALWAYS uses the Shipment-Response when only 1
			$this->setStatusCode($this->getLabelData(0)->getStatusCode());
			$this->setStatusText($this->getLabelData(0)->getStatusText());
			$this->setStatusMessage($this->getLabelData(0)->getStatusMessage());
		} else if($this->getStatusCode() === self::DHL_ERROR_WEAK_WARNING) {
			$noError = true;
			// Search in all shipments if an error/warning exists
			foreach($this->getLabelData() as &$labelData) {
				/**
				 * @var LabelData $labelData
				 */
				if($labelData->getStatusCode() !== self::DHL_ERROR_NO_ERROR) {
					$noError = false;
					break;
				}
			}
			
			if($noError) {
				$this->setStatusCode(self::DHL_ERROR_NO_ERROR);
				$this->setStatusText('ok');
			}
		}
	}
````

**Comment by RizzoRat** [comment]
IMHO a perfect workaround, meeting the expectations of new users and not breaking anything for existing users

**Comment by Petschko** [comment]
I think when there is only 1 Shipment its better to ignore the Global-Status and overwrite it, as someone wrote its not clear why the Global-Status is different and it's not explained by DHL...
So I use the Shipment-Status code. On multiple Shipments I check every shipment if there is an error if none it get manually set to DHL_ERROR_NO_ERROR, as you suggested (Makes sense IMO)

**Comment by Petschko** [comment]
Fixed: https://github.com/Petschko/dhl-php-sdk/pull/68
