### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by attikov** [Petschko/dhl-php-sdk#44]
$obj = new Product(ShipmentDetails::PRODUCT_TYPE_AUSTRIA_INTERNATIONAL_PACKAGE);
$obj->setName('DHL Paket International');

I would say, setName should add 'Austria' too for this  Product. For Austria Connect too.

Btw. Service PersonalHandover is obsolote, it has been replaced with namedPersonOnly.

**Comment by Petschko** [comment]
Hey, thank you so much for reporting this issue, can you please provide me example(s) what you want to change and why?

You told the "PersonalHandover"-Service is obsolete, where do you got that information from? If it's obsolete I can remove it of course

**Comment by attikov** [comment]
Hi,
After digging into the DHL documentations I'm not sure about the "Austria" thing, they have the same text as you, strange.

The "PersonalHandover" returns with invalid service under version 2.*.
Not sure about 1.*. Does it even still online?
In the forum of DHL a developer of them wrote that it has been superseded with "namedPersonOnly".

**Comment by Petschko** [comment]
Yeah that's why I used these.

I will change the Service when it's invalid!
Don't worry about Version 1, it has it's own function to generate the XML-Request, so even when the name is different I can change it exclusive for Version 1/2 etc

**Comment by Petschko** [comment]
I mark this Service as Deprecated in Version 0.3 (I will push it the next days), since I don't want support Version 1 anymore.
See also: https://github.com/Petschko/dhl-php-sdk/issues/2

**Comment by Petschko** [comment]
Done, see:
https://github.com/Petschko/dhl-php-sdk/commit/2248b7bddc6bd06c7a215ba7fe6f752ad803e419
https://github.com/Petschko/dhl-php-sdk/commit/0470fa8c5d606a483879ce921a25b20c9658f26c
