### ISSUE TITLE
Please Start to Tag Releases

### ISSUE THREAD

**Issue by ktomk** [Petschko/dhl-php-sdk#45]
Please tag revision 6e08515b2d10d9c76fe9cb7c954e112748fb4e3f as `0.0.1`.

**Comment by Petschko** [comment]
I don't have any releases right now~

Plus I'm unsure what you mean, can you please provide a description?

**Comment by ktomk** [comment]
Sure: It is announced that the package could be installed with composer, however if I follow the instructions to do so, it tells me that it does not so w/o version constraints:

~~~
$ composer require petschko/dhl-php-sdk
[...]
[InvalidArgumentException]                                                                                                                                                         
  Could not find a version of package petschko/dhl-php-sdk matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
[...]
~~~

A workaround then might be:

~~~
$ composer require petschko/dhl-php-sdk:dev-master@dev
~~~

However that never makes it through strict validation:

~~~
$ composer validate --strict                          
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
require.petschko/dhl-php-sdk : unbound version constraints (dev-master@dev) should be avoided
~~~

If the repository would have tags that packagist then use as versions, the problem would eb gone.

If you don't do releases (technically you actually do by hosting on github), just tag a version you deem currently the last most stable one and give it a low number like

    0.0.1

That would follow semantic versioning as everything below version 1 is not considered stable and allowed to break at any time.

Next time it is considered for another reference to install via composer raise the number at the end by one and tag it again.

I hope this description is neither too long nor to short. Please ask and/or provide feedback.

**Comment by Petschko** [comment]
I plan to do releases, but I had planed to just start them at Version 1.0.0

I could release the current version as "Pre-Release", would that help or does it need to be "Stable"?

**Comment by ktomk** [comment]
composer for validation needs a version number. if it is not stable (as I understand you), just don't start with 1.0.0 but with 0.x.x. E.g. in this case it's perhaps `v0.2.0` for the current moment. That tag would work.

**Comment by Petschko** [comment]
Okay, I think this should work... can you please test if it work now?

If I have an other stable version I have to create a new release and change the line in the composer.json?

I'm sorry, I'm really new to this Composer stuff... Thanks for the help so far =)

**Comment by ktomk** [comment]
@Petschko: Hey! The tag you did looks good. I just tested it and it works. Thanks a lot!

The change to the `composer.json` (ref: d9654960b7015a4f54b0b0c6be1ad372cc3738ac) however looks like an error. You do not need to change that file at all (you shouldn't even), so better revert that change, it says that the project requires itself (that makes no sense). You can do so on the commandline in the master branch with: 

~~~
$ git revert --no-edit d9654960b7015a4f54b0b0c6be1ad372cc3738ac
~~~

Push it back to Github and all should be fine.

**Comment by Petschko** [comment]
Alright that's good to know! Thank you a lot for the help =)

Btw: It's reverted

**Comment by ktomk** [comment]
For reference: This is how I installed it:

~~~
$ composer require "petschko/dhl-php-sdk:0.2.0"
~~~

that is w/ explicit version pinning (that exact version), in a less strict project this might be more common:

~~~
$ composer require "petschko/dhl-php-sdk:^0.2.0"
~~~

So if you now have a stable release (or regardless if you call it stable or not) and you wish to release the next version, choose the version number you see fit (you could orient w/ [semantic versioning](https://semver.org)), tag the commit and push the tag.

Each revision w/ a tag that looks like a version to composer (see here in the composer docs on how you can write the tags: https://getcomposer.org/doc/02-libraries.md#vcs-versioning).

**Comment by Petschko** [comment]
I see thank you so much for your help!

I have to read a bit more of the Composer-Doc, but I think I get the basics now =)

**Comment by ktomk** [comment]
:)
