### ISSUE TITLE
500er Servererror

### ISSUE THREAD

**Issue by giris-cloud** [Petschko/dhl-php-sdk#49]
Hi i have downloaded the dhl php sdk,
i set all Data in the test.php but it cames a 500er servererror.
Anyone have ideas?

http://burnout-trade.de/burnout_dhl/test.php

**Comment by Mwni** [comment]
Could be anything. Even a typo.
Check your error logs or prepend
```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```
to the script to find out.

**Comment by Petschko** [comment]
Hey, you need to provide us more details, like the Messages from the Error logs (see @Mwni's Comment)

Else it could be anything... I close this right now, feel free to open a new issue with more details, anytime =)

Btw: Make sure you have the [PHP-SOAP-Extension](http://php.net/manual/en/book.soap.php) enabled and installed.
