### ISSUE TITLE
Add getManifest

### ISSUE THREAD

**Issue by Ryback** [Petschko/dhl-php-sdk#50]
It would be nice if the getManifest action could be implemented.

According to api documentation with getManifest it is possible to get the daily pdf-summary files:
https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/operationen/getmanifest/beispieldaten

**Comment by VladislavsIgnatjevs** [comment]
Had this issue as well with a bit different integration I was doing for our company, DHL rep said that there no way to export eod manifest, this has to be recreated from response data

**Comment by Ryback** [comment]
Yeah, according to the api-documentation, the getManifest operation returns the manifest-pdf base64 encoded in the response data.

**Comment by Petschko** [comment]
Hey @Ryback ,

the `getManifest`-Function is already implemented. [(See here)](https://github.com/Petschko/dhl-php-sdk/blob/master/includes/BusinessShipment.php#L611)

If you have trouble with the function or when it does not work as you expect please let me know

**Comment by Petschko** [comment]
I implented this method in my Local-Code, I will push it when the Documentation is done

**Comment by Ryback** [comment]
Nice, that was fast!
Can`t wait to test it out!

**Comment by Petschko** [comment]
So I'm done

I would love when you can test the function `$dhl->getManifest('YYYY-MM-DD');` and tell me, if you got the Base64 PDF

You need to get the Base64 PDF-String from the response like this:
`$response->getManifestData();`

It seems, that you can't test this with the Test-Account...

**Comment by Ryback** [comment]
Tested it and it worked perfect! No problems here!

Thank you for the fast implementation!

**Comment by Petschko** [comment]
Alright, thanks for your help^^
