### ISSUE TITLE
Thermo Label Testuser

### ISSUE THREAD

**Issue by Magellanth** [Petschko/dhl-php-sdk#51]
Hi,

in test-mode the user is hardcoded set to "2222222222_01" but for thermo labels you need a different test-user.

https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/authentifizierung

> Test-User: 2222222222_01
> Test-User (Thermodrucker): 2222222222_03

overwriting the user with Credentials->setUser() wont work as any call of new BusinessShipment() with test-mode overwrites the credentials

**Comment by Petschko** [comment]
Thank you for the Info!

I also want redo the Credentials-Number (Auto-Assign the Number deppend on the Product-Type), so it's a good chance to add this!

What's the difference with the "Thermodrucker"-User?

**Comment by Magellanth** [comment]
The labels for thermo printers have only 103mm width so this type of label is mandatory for thermo printers.

Lot of companies still use thermo printers like "zebra" as they are much more reliable than standard laser printers, especially no problems with stickers stuck in the mechanics...

**Comment by Petschko** [comment]
Ah I see, so it's a different size, which makes sense to me, thanks for the fast answer.

**Comment by Petschko** [comment]
I implemented it in my side-branch: https://github.com/Petschko/dhl-php-sdk/commit/bea7ba477f6cd9f09d72c483b7a1b75602351826

I will merge it as soon as possible

**Comment by Petschko** [comment]
Merged: https://github.com/Petschko/dhl-php-sdk/pull/52
