### ISSUE TITLE
GoGreen deprecated?

### ISSUE THREAD

**Issue by MagellanT** [Petschko/dhl-php-sdk#55]
I can only find the deprecated Service::setGoGreen() function but there is no hint how to enable GoGreen in current version.
In the DHL Documentation there is still the option to set GoGreen https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/operationen/createshipmentorder/ioreference
- how can i set this?

**Comment by Petschko** [comment]
As far I know, you have to book this or activate it in your DHL-Account... One thing I can tell you for sure, it's not configurable via the API, see also:
https://github.com/Petschko/dhl-php-sdk/issues/23

**Comment by MagellanT** [comment]
Sorry i missed that issue, thanks.

**Comment by Petschko** [comment]
All fine =) I'm glad I could help you out
