### ISSUE TITLE
Authorization required

### ISSUE THREAD

**Issue by saadamin1223** [Petschko/dhl-php-sdk#57]
Does the credentials for https://xmlportal.dhl.com/login   also work in your sdk? and why it gives me syntax error or http 500 error on this line:
```php
$credentials = new \Petschko\DHL\Credentials(Credentials::TEST_NORMAL);
```
I have got only test credentials for dhl xml web services but i keep getting authorization required when i use it like this `$credentials = new \Petschko\DHL\Credentials();`
And in above case using TEST_NORMAL OR any other test mode i get syntax error????
please help me as quickly as possible thank you so much.

**Comment by saadamin1223** [comment]
i have changed the code the way you told me its still giving authorization
required. in attachment there is error in png and code in index.php

**Comment by saadamin1223** [comment]
i have putted site id and test password in apiuser and api pass

**Comment by Petschko** [comment]
Please provide the full error (Copy it)

Please provide your code, without personal data...

If thats an error with some PNG its something not from this SDK, since here are no PNG images at all

**Comment by saadamin1223** [comment]
i have taken the screen shot of error which i am getting on page in index.
php there is all code present.

**Comment by saadamin1223** [comment]
<?php

require_once __DIR__ . '/vendor/autoload.php';

	// You can initial the Credentials-Object with one of the pre-set Test-Accounts
//$credentials = new \Petschko\DHL\Credentials(); // Normal-Testuser
$credentials = new \Petschko\DHL\Credentials(\Petschko\DHL\Credentials::TEST_NORMAL);
// Now you just need to set your DHL-Developer-Data to it
$credentials->setApiUser('********************'); // Set the USERNAME (not E-Mail!) of your DHL-Dev-Account
$credentials->setApiPassword('************');




 // Set the Password of your DHL-Dev-Account
$sender = new \Petschko\DHL\Sender();

$sender->setName((string) 'Organisation Petschko'); // Can be a Person-Name or Company Name

// You need to seperate the StreetName from the Number and set each one to its own setter
// Example Full Address: "Oberer Landweg 12a" 
$sender->setStreetName((string) 'Oberer Landweg');
$sender->setStreetNumber((string) '12a'); // A Number is ALWAYS needed

$sender->setZip((string) '21035');
$sender->setCity((string) 'Hamburg');
$sender->setCountry((string) 'Germany');
$sender->setCountryISOCode((string) 'DE'); // 2 Chars ONLY


$shipmentDetails = new \Petschko\DHL\ShipmentDetails((string) $credentials->getEkp(10) . '0101'); // Ensure the 0101 at the end (or the number you need for your Product)

$shipmentOrder = new \Petschko\DHL\ShipmentOrder();


$receiver = new \Petschko\DHL\Receiver();


$receiver->setName((string) 'Organisation Petschko'); // Can be a Person-Name or Company Name

// You need to seperate the StreetName from the Number and set each one to its own setter
// Example Full Address: "Oberer Landweg 12a" 
$receiver->setStreetName((string) 'Oberer Landweg');
$receiver->setStreetNumber((string) '12a'); // A Number is ALWAYS needed

$receiver->setZip((string) '21035');
$receiver->setCity((string) 'Hamburg');
$receiver->setCountry((string) 'Germany');
$receiver->setCountryISOCode((string) 'DE'); // 2 Chars ONLY


$shipmentOrder->setShipmentDetails($shipmentDetails); // \Petschko\DHL\ShipmentDetails Object
$shipmentOrder->setSender($sender); // \Petschko\DHL\Sender Object
$shipmentOrder->setReceiver($receiver);


$dhl = new \Petschko\DHL\BusinessShipment($credentials);



// Add all Required (For a CREATE-Shipment-Request) Classes
$dhl->addShipmentOrder($shipmentOrder);



$dhl->setLog((bool) true);




$dhl->setLabelResponseType((string) \Petschko\DHL\BusinessShipment::RESPONSE_TYPE_B64); // Default: null -> Uses DHL-Default



$response = $dhl->createShipment();




if($response === false) {
	// Do your Error-Handling here

	// Just to show all Errors
	var_dump($dhl);
	var_dump($dhl->getErrors()); // Get the Error-Array
} else {
	// Handle the Response here

	// Just to show the whole Response-Object
	var_dump($response);
}























``

**Comment by saadamin1223** [comment]
[index.php.tar.gz](https://github.com/Petschko/dhl-php-sdk/files/2423561/index.php.tar.gz)

**Comment by saadamin1223** [comment]
> I don't see any images in your Comments at all.
> 
> You know, if you reply to the E-Mail, that this will send as Comment on Github, without attachments

sorry  ididnt knew about that i havesent know in comment can you please check thanx

**Comment by Petschko** [comment]
Authorization required means, that your Login doesn't work. There are several Problems with the login:

- Do you used your E-Mail as Account-Name? (Do **NOT** use the E-Mail as Username, use the AccountNAME)
- Does your password has some specific special chars? Try change the password, some chars doesn't work, may I need to encode them in some way, I really have to lookup this

> And in above case using TEST_NORMAL OR any other test mode i get syntax error????
About your Syntax-Error, what was about it?

**Comment by saadamin1223** [comment]
the problem of syntax error was resolved with your suggestion above after
giving path before credentials, i will try password changing and will reply
you later if it gets succeeded or not. Thankyou for your help. 😊

**Comment by Petschko** [comment]
I've added the missing namespace to the "Getting started"-File: https://github.com/Petschko/dhl-php-sdk/commit/bcb64adc548ce7cd0ef161d885f6b36c98601a7f

Thanks for pointing it out!

If you need help or find an other issue please let me know! =)
