### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by felunka** [Petschko/dhl-php-sdk#60]
Hi! I am trying to create a new shipment through the API Using the code in test.php...
The Problem is, that i always get an error, when creating a shipment: Unauthorized. The login credentials are correct (Dev ID and Password) and I can login just fine with them on the website.

`<?php
require_once(__DIR__ . '/dhl-php-sdk/includes/_nonComposerLoader.php');
	
use Petschko\DHL\BusinessShipment;
use Petschko\DHL\Credentials;
use Petschko\DHL\Receiver;
use Petschko\DHL\ReturnReceiver;
use Petschko\DHL\Sender;
use Petschko\DHL\Service;
use Petschko\DHL\ShipmentOrder;
use Petschko\DHL\ShipmentDetails;

	//$testMode = Credentials::DHL_BUSINESS_TEST_USER_THERMO; // Uses the thermo-printer test user
	$reference = '1'; // You can use anything here (max 35 chars)

	$credentials = new Credentials(Credentials::TEST_NORMAL);
	var_dump($credentials);
	echo '<br>';
	
	// Set your API-Login
	$credentials->setApiUser('#######');			// Test-Mode: Your DHL-Dev-Account (Developer-ID NOT E-Mail!!) | Production: Your Applications-ID
	$credentials->setApiPassword('##########');
	var_dump($credentials);
	echo '<br>';

	$sender = new Sender();
	//Address replaced for privacy..
	$sender->setName((string) 'ABC'); // Can be a Person-Name or Company Name

	$sender->setStreetName((string) 'ABC');
	$sender->setStreetNumber((string) '5'); // A Number is ALWAYS needed

	$sender->setZip((string) '12345');
	$sender->setCity((string) 'ABC');
	$sender->setCountry((string) 'Germany');
	$sender->setCountryISOCode((string) 'DE'); // 2 Chars ONLY
	
	$shipmentDetails = new ShipmentDetails($credentials->getEkp(10) . '0101');
	
	//Getting userdata fro DB cut out...

	// receiver details
	$receiver = new Receiver();
	$receiver->setName($firstname . ' ' . $lastname);
	$receiver->setStreetName($str);
	$receiver->setStreetNumber($number);
	$receiver->setZip($plz);
	$receiver->setCity($town);
	$receiver->setCountry('Germany');
	$receiver->setCountryISOCode('DE');
	
	
	$dhl = new BusinessShipment($credentials);
	echo '<br>';
	var_dump($dhl);
	echo '<br>';
	
	$shipmentOrder = new ShipmentOrder();
	$shipmentOrder->setSequenceNumber($reference); // Just needed to identify the shipment if you do multiple
	$shipmentOrder->setSender($sender);
	$shipmentOrder->setReceiver($receiver); // You can set these Object-Types here: DHL_Filial, DHL_Receiver & DHL_PackStation
	$shipmentOrder->setShipmentDetails($shipmentDetails);
	$shipmentOrder->setLabelResponseType(BusinessShipment::RESPONSE_TYPE_URL);
	
	$dhl->addShipmentOrder($shipmentOrder);
	$response = $dhl->createShipment();

	if($response !== false) {
		echo 'Erfolg! Klicke <a href="' . $response["label_url"] . '">hier</a> um das Label anzuzeigen.<br><br>';
		var_dump($response);
	  
	} else {
		var_dump($dhl->getErrors());
	}

?>`

**Comment by Petschko** [comment]
Hey!
Please make sure to change your password, since you actually submit it here! Also do not reuse this password on any other sites (change it if you actually use it somewhere else), since people still can find it here when they look onto the Edit-History!

About the unauthorized error, it happened more often that DHL seems to bug sometimes with the verification. In most cases people were able to use this project after changing their password again

**Comment by panconjugo** [comment]
Hi Peter,

Thanks for your reply, now it is working, I used the test.php file you have
in the repository and with that file works great, I just edited the parts
according to my needs.

Thanks.

**Comment by labSupport** [comment]
I'm getting the same error.

First thing I found out is, that you need to explicitly set test mode for the BusinessShipment instance. Although the parameter is mentioned in the "getting started" guide it wasn't clear to me, that you need to set this, when using test credentials. Maybe this should be clarified.

Unfortunately I still get the "Unauthorized" error with a pretty simple request. I tested this with the default test credentials and with my own developer account. Any idea what could cause this issue?

**Comment by labSupport** [comment]
To clarify, I just copied the example data from the getting started guide without changing the code. Result "Unauthorized"

```
  $credentials = new \Petschko\DHL\Credentials(/* Optional: Test-Modus */ \Petschko\DHL\Credentials::TEST_NORMAL); // Normal-Testuser

  $sender = new \Petschko\DHL\Sender();
  $sender->setName((string) 'Organisation Petschko'); // Can be a Person-Name or Company Name

  // You need to seperate the StreetName from the Number and set each one to its own setter
  // Example Full Address: "Oberer Landweg 12a"
  $sender->setStreetName((string) 'Oberer Landweg');
  $sender->setStreetNumber((string) '12a'); // A Number is ALWAYS needed

  $sender->setZip((string) '21035');
  $sender->setCity((string) 'Hamburg');
  $sender->setCountry((string) 'Germany');
  $sender->setCountryISOCode((string) 'DE'); // 2 Chars ONLY

  $receiver = new \Petschko\DHL\Receiver();
  $receiver->setName((string) 'Organisation Petschko'); // Can be a Person-Name or Company Name

  // You need to seperate the StreetName from the Number and set each one to its own setter
  // Example Full Address: "Oberer Landweg 12a"
  $receiver->setStreetName((string) 'Oberer Landweg');
  $receiver->setStreetNumber((string) '12a'); // A Number is ALWAYS needed

  $receiver->setZip((string) '21035');
  $receiver->setCity((string) 'Hamburg');
  $receiver->setCountry((string) 'Germany');
  $receiver->setCountryISOCode((string) 'DE'); // 2 Chars ONLY

  $shipmentDetails = new \Petschko\DHL\ShipmentDetails((string) $credentials->getEkp(10) . '0101'); // Ensure the 0101 at the end (or the number you need for your Product)
  $shipmentDetails->setProduct((string) \Petschko\DHL\ShipmentDetails::PRODUCT_TYPE_INTERNATIONAL_PACKAGE);

  $shipmentOrder = new \Petschko\DHL\ShipmentOrder();

  $shipmentOrder->setShipmentDetails($shipmentDetails); // \Petschko\DHL\ShipmentDetails Object
  $shipmentOrder->setSender($sender); // \Petschko\DHL\Sender Object
  $shipmentOrder->setReceiver($receiver); // \Petschko\DHL\Receiver, \Petschko\DHL\PackStation or the \Petschko\DHL\Filial Object

  $dhl = new \Petschko\DHL\BusinessShipment($credentials, TRUE);
  $dhl->addShipmentOrder($shipmentOrder);

  $response = $dhl->createShipment();
  if ($response === FALSE) {
    // Do your Error-Handling here

    // Just to show all Errors
    var_dump($dhl->getErrors()); // Get the Error-Array
  }
  else {
    // Handle the Response here

    // Just to show the whole Response-Object
    var_dump($response);
  }
```

**Comment by labSupport** [comment]
It works now. Might have been a temporary issue in my side. Never mind.

**Comment by fmenz** [comment]
Hello,
I have the same Problem as @felunka and @labSupport. Using the Example code always returns an Array containing one String-Element "Unauthorized". No matter if installed the Code by Composer or the non-Composer Version. Login Credentials (Test User and Password and my Developer account) are correct.

When i test with the tool SoapUI (recommended on the DHL Developer site) everything works fine, I can test everything an get the SOAP-XML Answer, so the endpoint Service does not seem to be the Problem. 
Anyone any Idea? Thanks for help!

**Comment by rwander2906** [comment]
@fmenz: The reason is, that new customers of dhl-developer-programm only get access to the 3.0 Version of the API and @Petschko is still developing on it. Only chance is to wait. Or may help Petschko ;-)
