### ISSUE TITLE
validateShipment returning statuscode 1 or 0 on refresh

### ISSUE THREAD

**Issue by panconjugo** [Petschko/dhl-php-sdk#61]
Hey,

I am trying to test the validateShipment function doing this:

`$response = $dhl->validateShipment($shipmentOrder);`

and I got an object with the data which I can use to validate, so then I do this:

```
$status_text = $response->getStatusText();
$status_code = $response->getStatusCode();

if($status_text == "ok" && $status_code == 0){

  echo "success";

}
```

But curiously, when I refresh the page, sometimes I get $status_code = 0 and sometimes I get $status_code = 1. Why is that? Here is the response object when everything works well.

`object(Petschko\DHL\Response)#943 (8) { ["manifestData":"Petschko\DHL\Response":private]=> NULL ["statusCode":"Petschko\DHL\Response":private]=> int(0) ["statusText":"Petschko\DHL\Response":private]=> string(2) "ok" ["statusMessage":"Petschko\DHL\Response":private]=> string(45) "Der Webservice wurde ohne Fehler ausgeführt." ["labelData":"Petschko\DHL\Response":private]=> array(1) { [0]=> object(Petschko\DHL\LabelData)#944 (12) { ["statusCode":"Petschko\DHL\LabelData":private]=> int(0) ["statusText":"Petschko\DHL\LabelData":private]=> string(2) "ok" ["statusMessage":"Petschko\DHL\LabelData":private]=> string(45) "Der Webservice wurde ohne Fehler ausgeführt." ["sequenceNumber":"Petschko\DHL\LabelData":private]=> string(1) "1" ["shipmentNumber":"Petschko\DHL\LabelData":private]=> NULL ["label":"Petschko\DHL\LabelData":private]=> NULL ["returnLabel":"Petschko\DHL\LabelData":private]=> NULL ["exportDoc":"Petschko\DHL\LabelData":private]=> NULL ["codLabel":"Petschko\DHL\LabelData":private]=> NULL ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) } } ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) }`

And here is the object when the status code is 1:

`object(Petschko\DHL\Response)#943 (8) { ["manifestData":"Petschko\DHL\Response":private]=> NULL ["statusCode":"Petschko\DHL\Response":private]=> int(1) ["statusText":"Petschko\DHL\Response":private]=> string(26) "Some Shipments had errors." ["statusMessage":"Petschko\DHL\Response":private]=> string(48) "ok;Der Webservice wurde ohne Fehler ausgeführt." ["labelData":"Petschko\DHL\Response":private]=> array(1) { [0]=> object(Petschko\DHL\LabelData)#944 (12) { ["statusCode":"Petschko\DHL\LabelData":private]=> int(0) ["statusText":"Petschko\DHL\LabelData":private]=> string(2) "ok" ["statusMessage":"Petschko\DHL\LabelData":private]=> string(45) "Der Webservice wurde ohne Fehler ausgeführt." ["sequenceNumber":"Petschko\DHL\LabelData":private]=> string(1) "1" ["shipmentNumber":"Petschko\DHL\LabelData":private]=> NULL ["label":"Petschko\DHL\LabelData":private]=> NULL ["returnLabel":"Petschko\DHL\LabelData":private]=> NULL ["exportDoc":"Petschko\DHL\LabelData":private]=> NULL ["codLabel":"Petschko\DHL\LabelData":private]=> NULL ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) } } ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) }`

Do you know the reason of this? am I missing any other setting? Should I just pay attention to the labeldata array? because there it seems to always display the correct code (notice that I am using a correct address for sender and receiver but I am testing with the sender in this case).

Thanks.

**Comment by Petschko** [comment]
See also here: https://github.com/Petschko/dhl-php-sdk/issues/43

**Comment by panconjugo** [comment]
I also checked that entry, they seems to have exactly the same problem. 

I think the LabelData array returned in the $response is better, am I right? Because I am testing and it has the child statuscode and statustext displaying the data correctly even when I refresh.

I tried this **(with a wrong city)**:

`var_dump($response->getLabelData()); `

and returned this:

`array(1) { [0]=> object(Petschko\DHL\LabelData)#944 (12) { ["statusCode":"Petschko\DHL\LabelData":private]=> int(1) ["statusText":"Petschko\DHL\LabelData":private]=> string(30) "Weak validation error occured." ["statusMessage":"Petschko\DHL\LabelData":private]=> string(239) "Der Ort ist zu dieser PLZ nicht bekannt. Die Sendung ist trotzdem leitcodierbar und es wurde ein Versandschein erzeugt.;Der Ort ist zu dieser PLZ nicht bekannt. Die Sendung ist trotzdem leitcodierbar und es wurde ein Versandschein erzeugt." ["sequenceNumber":"Petschko\DHL\LabelData":private]=> string(1) "1" ["shipmentNumber":"Petschko\DHL\LabelData":private]=> NULL ["label":"Petschko\DHL\LabelData":private]=> NULL ["returnLabel":"Petschko\DHL\LabelData":private]=> NULL ["exportDoc":"Petschko\DHL\LabelData":private]=> NULL ["codLabel":"Petschko\DHL\LabelData":private]=> NULL ["version":"Petschko\DHL\Version":private]=> string(3) "2.2" ["mayor":"Petschko\DHL\Version":private]=> int(2) ["minor":"Petschko\DHL\Version":private]=> int(2) } } `

So I have 2 problems with that...first the statusMessage data is displayed twice and second this statusMessage is telling me this:

`Der Ort ist zu dieser PLZ nicht bekannt. Die Sendung ist trotzdem leitcodierbar und es wurde ein Versandschein erzeugt`

And I need to only generate the shipping ticket, I mean the whole shipping proccess, when everything is correct. I don't want to generate the shipping ticket when the message is **"Der Ort ist zu dieser PLZ nicht bekannt"**

Any idea about this? thanks a lot.
