### ISSUE TITLE
How to create a multi-package-sending?

### ISSUE THREAD

**Issue by BernardTeske** [Petschko/dhl-php-sdk#63]
I'm trying to send multiple packages. I added two by using

`$dhl->addShipmentOrder($shipmentOrder);`

but the packages get differend numbers and on each label there is the number „Anzahl“ 1/1. How can I change this? There should be a 1/2 and 2/2.

**Comment by BernardTeske** [comment]
It seams that this is not supported?! Found something like that after hours of googling...

**Comment by Petschko** [comment]
The "addShipmentOrder" function is not for changing the amount of a Shipment. It just allows you to request multiple Shipment-Labels in via SOAP (Up to 30)

I think I read something similar to that the function you want don't exists
