### ISSUE TITLE
labelFormat Option

### ISSUE THREAD

**Issue by felunka** [Petschko/dhl-php-sdk#66]
Is there any way to set the labelFormat Option?

**Comment by Magellanth** [comment]
As far as i know the format of the label is defined by the user settings inside the Geschäftskundenportal and not subject to the API.

**Comment by felunka** [comment]
That is what I thought as well. I asked the support if there is any way to do this and they told me it is a normal feature (I think a new one).
Check out the doku right at the bottom "5. | labelFormat | String | Optional":
https://entwickler.dhl.de/group/ep/wsapis/gerschaftskundenversand-3.0/operationen/createshipmentorder/ioreference

**Comment by Magellanth** [comment]
Ok yes thats new - in the 2.2 doc this option is missing, only the 3.0 doc lists it.
But the docu only lists the parameter wihtout any possible values or description :/

As 3.0 is not yet supported by this project your answer is no, there is no way for now.

**Comment by felunka** [comment]
Thank you for your answer! Let me know, when that changes!

**Comment by Petschko** [comment]
It should work now in the dev branch, you can test it^^

Big thanks to @OliverTempel
