### ISSUE TITLE
GoGreen used in Version 3?

### ISSUE THREAD

**Issue by Petschko** [Petschko/dhl-php-sdk#69]
Hey,

I just wonder if the GoGreen field has a purpose in Version 3 or is it still a field which does nothing?

**Comment by cottton** [comment]
I too would like to know that.
I created the xml request by my own and tried to send no go green option 
and go green option disabled|inactive.

Result: still prints go green on label (sandbox).

**Comment by Petschko** [comment]
Yeah the 2.0 Version ignores the GoGreen, I hope it may work now with 3.x

**Comment by cottton** [comment]
> Yeah the 2.0 Version ignores the GoGreen, I hope it may work now with 3.x

I meant i created the xml my self (without `dhl-php-sdk`) in version 3.
_Forgot to mention that._

**Comment by Petschko** [comment]
Probably GoGreen is still unused... I wonder why they don't remove it from the code...

**Comment by cottton** [comment]
Just found something (in german):
https://www.dhl.de/de/privatkunden/kampagnenseiten/dhl-nachhaltigkeit.html
and
https://www.dhl.de/content/dam/images/pdf/GK/Services/dhl-gogreen-infoblatt-012019.pdf

    Deutschlandweiter Versand
    Sie verschicken automatisch alle Päckchen und Pakete zu 100 % klimaneutral - 
    ohne zusätzliche Kosten.

    Weltweiter Versand
    In andere Länder können Sie gegen einen geringen Aufpreis 
    ebenfalls klimafreundlich verschicken.

    + 0,20 EUR im EU-weiten und
    + 0,70 EUR im weltweiten Versand


So in germany you pay nothing for the GoGreen option. Default enabled.
In EU you pay 20 ct
and worldwide 70 ct.

BUT on the 2nd paper the say 

    Attraktiver Preis
    0,02 € zzgl. MwSt. zusätzlich zum Paketpreis

    Der Service ist bereits Bestandteil Ihres Vertrags und kann direkt über die DHL 
    Versandlogistiksysteme (Funktion Versenden im Geschäftskundenportal und System Easylog) 
    beauftragt werden. Selbstverständlich steht der Service Ihnen auch zur Verfügung, 
    wenn Sie Ihre Versandlogistiksysteme eigenständig programmieren

DHL is so f* up with its documentation.
This is not the first time i read different descriptions on their documents -.-

I tried to set the service to `<GoGreed><active>0</...` with 
DE to DE 
and DE to GB.
Still GoGreen enabled.
Also if you do not set this service ofc -.-

**Comment by Petschko** [comment]
Yeah but that's about "GoGreen", not the GoGreen fireld in the code.

I think if the GoGreen field does nothing in Version 3.x it will do the same like in Version 2.x (Nothing)

In Version 2 you had to setup the GoGreen value in your Account, while the Code "GoGreen" did nothing

**Comment by cottton** [comment]
INFO
_anwer from DHL_

> GoGreen ist kein Service. Wenn dies vertraglich vereinbart ist, wird automatisch diese Abrechnungsnummer bei Nutzung mit dem Logo versehen. Das läuft rein über den Vertrag und kann nicht über die API ein oder ausgeschaltet werden (war mal so gedacht).

Seems like the sandbox just prints the gogreen by default.
