### ISSUE TITLE
how to connect to production mode using provided credentials

### ISSUE THREAD

**Issue by jyyyy** [Petschko/dhl-php-sdk#70]
Hello 
I want to login to dhl api using the provided credentials 
site ID - account Number - password 
please could you help me and show me how to login in with production mode 

and also please let me know if could generate shipping label (pdf) with your code 

thanks

**Comment by Petschko** [comment]
Hey, please read this summary I wrote~

https://github.com/Petschko/dhl-php-sdk/blob/master/examples/getting-started.md
