### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by kasoft** [Petschko/dhl-php-sdk#72]
On the Frontpage is written: 
PHP-Version 5.4 or higher (It may work on older Versions, but I don't offer Support for these) 

If you Install via composer
Problem 1
    - petschko/dhl-php-sdk dev-master requires php >=7.2.0 -> your PHP version (7.1.30) does not satisfy that requirement.

So please change the PHP Version in the composer File or on the Frontpage :-)
I hope it's working with PHP 7.1

Thanks!

**Comment by Petschko** [comment]
Probably I made a small misstake when pushing...

The new API 3.0 Version is only available with 7.2, but its not tested enough and still misses some features.

I will take a look tomorrow to ensure no 7.x methods were used and I change the php-version in the composer file back to 5.4.
But it will need php 7.2 in the long run (if you want use API 3.0 from DHL)

**Comment by Petschko** [comment]
Sorry was a bit distracted doing holidays, its now changed back~
