### ISSUE TITLE
Endpoints for .com?

### ISSUE THREAD

**Issue by futurewebsites** [Petschko/dhl-php-sdk#75]
DHL have given me the following endpoints -> https://wsbexpress.dhl.com:443/snd
pt/expressRateBook?WSDL

I notice the ones in this repo are all .de endpoints can I simply change them in BusinessShipment.php?

**Comment by Petschko** [comment]
You can define a custom-Endpoint, by using the `setCustomAPIURL` function from the BusinessShipment Class.

Just an example how to define it:

```php
$dhl = new \Petschko\DHL\BusinessShipment($credentials);
$dhl->setCustomAPIURL('http://myserver.com/myAPIFile.wsdl');
```
