### ISSUE TITLE
returnLabel is empty

### ISSUE THREAD

**Issue by trebaxa** [Petschko/dhl-php-sdk#76]
The "ReturnReceiver" is set, but the response field "ReturnLabel" is empty. Any help?

**Comment by Petschko** [comment]
The Field "ReturnLabel" is only used when you set a Option in the GKP (Geschäftskundenportal) to true. Usually the Return-Label is default inside the normal-label pdf

**Comment by trebaxa** [comment]
Thx for answer. Even the standard DHL label has only 1 page, but no returnlabel. It includes only the label itself.

**Comment by Petschko** [comment]
At this point it would be helpful to see how you did the request~

**Comment by trebaxa** [comment]
$service = new Service();
        $shipmentDetails = new ShipmentDetails($credentials->getEkp(10) . '0101');       
        $shipmentDetails->setNotificationEmail($order['email']); 
        $shipmentDetails->setService($service); 
        $shipmentDetails->setWeight($order['gewicht']);
$returnReceiver = new ReturnReceiver();
        $returnReceiver->setName($sendername);
        $returnReceiver->setStreetName($this->gbl_config['adr_street']);
        $returnReceiver->setStreetNumber($this->gbl_config['adr_hausnr']);
        $returnReceiver->setZip($this->gbl_config['adr_plz']);
        $returnReceiver->setCity($this->gbl_config['adr_town']);
        $returnReceiver->setCountry(ucfirst($country_sender['land']));
        $returnReceiver->setCountryISOCode($this->gbl_config['adr_country']);
        $returnReceiver->setEmail($this->gbl_config['adr_service_email']); // These are super optional, it will printed on the label, can set under receiver as well

 // Required just Credentials also accept Test-Mode and Version
        $dhl = new BusinessShipment($credentials, /*Optional*/ $testMode, /*Optional*/ $version);

        // You can add your own API-File (if you want to use a remote one or your own) - else you don't need this
        //$dhl->setCustomAPIURL('http://myserver.com/myAPIFile.wsdl');

        // Don't forget to assign the created objects to the ShipmentOrder Object!
        $shipmentOrder = new ShipmentOrder();
        $shipmentOrder->setSequenceNumber($reference); // Just needed to identify the shipment if you do multiple
        $shipmentOrder->setSender($sender);
        $shipmentOrder->setReceiver($receiver); 
        $shipmentOrder->setReturnReceiver($returnReceiver); // Needed if you want print a return label
        $shipmentOrder->setShipmentDetails($shipmentDetails);
        $shipmentOrder->setLabelResponseType(BusinessShipment::RESPONSE_TYPE_URL);

        // Add the ShipmentOrder to the BusinessShipment Object, you can add up to 30 ShipmentOrder Objects in 1 call
        $dhl->addShipmentOrder($shipmentOrder);
$response = $dhl->createShipment();

**Comment by Petschko** [comment]
Did you used the Test-Modus? Ive read something in their forums about test-mode and return labels where not shown...

They had even a bug ~1-2 weeks ago, which is now fixed. The bug was on test & productive systems and also caused return labels not shown.
