### ISSUE TITLE
Release of Version

### ISSUE THREAD

**Issue by trebaxa** [Petschko/dhl-php-sdk#79]
Hey guys,

when do you think version 3 will be implemented?

cheers,
Harald

**Comment by Petschko** [comment]
I have currently some trouble in RL, so I don't have that much time. Its almost ready to ship, you can actually test it by using the dev branch :) - Mostly its done, I need to re-write the documentation for Version 3

**Comment by Petschko** [comment]
Just a note, I will update it these days, so I close a couple of issues like this, which are basically about V. 3

I dont have that much trouble anymore and more time now =)

**Comment by trebaxa** [comment]
Hello my friend,
just want to know how the progress is on building V3.0 compatibility? Thanks for reply.
