### ISSUE TITLE
Failure: Unauthorized

### ISSUE THREAD

**Issue by LukaszNiziolDWG** [Petschko/dhl-php-sdk#83]
I create a project according to the documentation. Unfortunately I am getting an error. Can anyone help me? Where to find a solution? I am losing faith that it will succeed.

// You can initial the Credentials-Object with one of the pre-set Test-Accounts
        $credentials = new \Petschko\DHL\Credentials(/* Optional: Test-Modus */ Credentials::TEST_NORMAL); // Normal-Testuser
        $credentials = new \Petschko\DHL\Credentials(/* Optional: Test-Modus */ Credentials::TEST_THERMO_PRINTER); // Thermo-Printer-Testuser
        // Now you just need to set your DHL-Developer-Data to it
        $credentials->setApiUser("xxxxxx"); // Set the USERNAME (not E-Mail!) of your DHL-Dev-Account
        $credentials->setApiPassword("xxxxxx"); // Set the Password of your DHL-Dev-Account

        $credentials = new \Petschko\DHL\Credentials(/* Optional: Test-Modus */ \Petschko\DHL\Credentials::TEST_NORMAL); // Normal-Testuser

        $sender = new \Petschko\DHL\Sender();
        $sender->setName((string) 'Organisation Petschko'); // Can be a Person-Name or Company Name
        // You need to seperate the StreetName from the Number and set each one to its own setter
        // Example Full Address: "Oberer Landweg 12a"
        $sender->setStreetName((string) 'Oberer Landweg');
        $sender->setStreetNumber((string) '12a'); // A Number is ALWAYS needed

        $sender->setZip((string) '21035');
        $sender->setCity((string) 'Hamburg');
        $sender->setCountry((string) 'Germany');
        $sender->setCountryISOCode((string) 'DE'); // 2 Chars ONLY

        $receiver = new \Petschko\DHL\Receiver();
        $receiver->setName((string) 'Organisation Petschko'); // Can be a Person-Name or Company Name
        // You need to seperate the StreetName from the Number and set each one to its own setter
        // Example Full Address: "Oberer Landweg 12a"
        $receiver->setStreetName((string) 'Oberer Landweg');
        $receiver->setStreetNumber((string) '12a'); // A Number is ALWAYS needed

        $receiver->setZip((string) '21035');
        $receiver->setCity((string) 'Hamburg');
        $receiver->setCountry((string) 'Germany');
        $receiver->setCountryISOCode((string) 'DE'); // 2 Chars ONLY

        $shipmentDetails = new \Petschko\DHL\ShipmentDetails((string) $credentials->getEkp(10) . '0101'); // Ensure the 0101 at the end (or the number you need for your Product)
        $shipmentDetails->setProduct((string) \Petschko\DHL\ShipmentDetails::PRODUCT_TYPE_INTERNATIONAL_PACKAGE);

        $shipmentOrder = new \Petschko\DHL\ShipmentOrder();

        $shipmentOrder->setShipmentDetails($shipmentDetails); // \Petschko\DHL\ShipmentDetails Object
        $shipmentOrder->setSender($sender); // \Petschko\DHL\Sender Object
        $shipmentOrder->setReceiver($receiver); // \Petschko\DHL\Receiver, \Petschko\DHL\PackStation or the \Petschko\DHL\Filial Object

        $dhl = new \Petschko\DHL\BusinessShipment($credentials, TRUE);
        $dhl->addShipmentOrder($shipmentOrder);

        $response = $dhl->createShipment();

        if ($response === FALSE) {
            // Do your Error-Handling here
            // Just to show all Errors
            var_dump($dhl->getErrors()); // Get the Error-Array
        } else {
            // Handle the Response here
            // Just to show the whole Response-Object
            var_dump($response);
        }

**Result:** array(1) { [0]=> string(12) "Unauthorized" }

**Comment by Petschko** [comment]
https://github.com/Petschko/dhl-php-sdk/issues/60#issuecomment-513126033

**Comment by Petschko** [comment]
Alternatively you can use the DEV-Branch which is the Beta-Version for Version 3, the Main-Branch ist still only for 2
